name: Generate Packages
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev zstd

      - name: Build repo metadata
        run: |
          dpkg-scanpackages --multiversion debs /dev/null > Packages.raw
          sed -E 's/^Section:.*$/Section: Tweaks/' Packages.raw > Packages
          zstd -f Packages -o Packages.zst
          rm -f Packages.raw
          cat > Release <<EOF
Origin: XY
Label: XY
Suite: stable
Codename: stable
Version: 1.0
Architectures: iphoneos-arm64 iphoneos-arm64e
Components: main
Description: XY
Icon: CydiaIcon.png
EOF
          apt-ftparchive release . >> Release

      - name: Commit & Push changes
        run: |
          git config --global user.name "${{ shturl.cc/Cp }}"
          git config --global user.email "${{ shturl.cc/Cp }}@users.noreply.github.com"
          git add Packages Packages.zst Release
          git commit -m "Auto update repo metadata" || echo "No changes to commit"
          git push
