# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Update Sileo Repository

on: 
  push:
    branches: 
      - master  # 请根据需要修改为你仓库的默认分支名称
    paths:
      - 'debs/*.deb'  # 监控 /debs/ 文件夹下的所有.deb文件的上传

jobs:
  update-repo:
    runs-on: ubuntu-latest  # 使用最新ubuntu环境

    steps:
      - name: Checkout
        uses: actions/checkout@v2  # 检出仓库代码

      - name: Install dpkg
        run: sudo apt-get update && sudo apt-get install -y dpkg

      - name: Generate Packages file
        run: |
          dpkg-scanpackages --multiversion debs >> Packages
          cat Packages | bzip2 > Packages.bz2
          cat Packages | gzip > Packages.gz

      - name: Pull Changes
        run: git pull origin main  # 拉取远程库的最新改动
     
      - name: Push Updates
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -f Packages Packages.gz Packages.bz2
          git commit -m "Update Sileo Packages"
          git push origin main     # 推送合并后的改动到远程
          git push  # 推送更新到仓库
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用GitHub自动生成的Token进行操作
