# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Cydia/Sileo Repository Update

on:
  push:
    branches:
      - master  # 确保这里是你想要的分支名
    paths:
      - 'debs/*.deb'  # 工作流将在此路径下的.deb文件更改后触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # 使用最新的Ubuntu虚拟环境来运行工作流处理

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # 检出仓库的代码

      - name: Set up Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"  # 设置 Git 的用户信息

      - name: Sync with Remote
        run: |
          git fetch
          git reset --hard origin/master  # 重置代码到远程分支的最新状态

      - name: Install dpkg
        run: sudo apt-get update && sudo apt-get install -y dpkg  # 安装 dpkg 工具

      - name: Generate Packages file
        run: |
          dpkg-scanpackages -m debs /dev/null > Packages  # 生成 Packages 文件
          gzip -kf Packages   # 创建 Packages.gz 压缩文件
          bzip2 -kf Packages  # 创建 Packages.bz2 压缩文件

      - name: Commit and Push Changes
        run: |
          git add Packages Packages.gz Packages.bz2  # 将新生成的文件添加到 git
          git commit -m "Update Cydia/Sileo packages" || exit 0   # Commit 变更，如果没有变更则退出
          git push origin master # 将变更推送回远程仓库

      - name: Clear Old Artifacts
        if: always()
        run: |
          rm -f Packages Packages.gz Packages.bz2  # 最终清理工作目录
